INFO: 2022-Apr-22 15:07:21: Messages will be sent to messages.msg.
INFO: 2022-Apr-22 15:07:21: Simulation box is periodic with size (lx,ly,lz) = (100,100,10).
INFO: 2022-Apr-22 15:07:21: Generated group 'all' containing all particles.
INFO: 2022-Apr-22 15:07:21: Reading particle coordinates from file: plane.dat
WARNING: 2022-Apr-22 15:07:21: Input format style '# id type radius' is deprecated and will be removed in a future version.
INFO: 2022-Apr-22 15:07:21: Column 1 of input file is : id.
INFO: 2022-Apr-22 15:07:21: Column 2 of input file is : type.
INFO: 2022-Apr-22 15:07:21: Column 3 of input file is : radius.
INFO: 2022-Apr-22 15:07:21: Column 4 of input file is : x.
INFO: 2022-Apr-22 15:07:21: Column 5 of input file is : y.
INFO: 2022-Apr-22 15:07:21: Column 6 of input file is : z.
INFO: 2022-Apr-22 15:07:21: Column 7 of input file is : vx.
INFO: 2022-Apr-22 15:07:21: Column 8 of input file is : vy.
INFO: 2022-Apr-22 15:07:21: Column 9 of input file is : vz.
INFO: 2022-Apr-22 15:07:21: Column 10 of input file is : nx.
INFO: 2022-Apr-22 15:07:21: Column 11 of input file is : ny.
INFO: 2022-Apr-22 15:07:21: Column 12 of input file is : nz.
INFO: 2022-Apr-22 15:07:21: Column 13 of input file is : omega.
INFO: 2022-Apr-22 15:07:21: Read data for 3183 particles.
INFO: 2022-Apr-22 15:07:21: There are 2 distinct particle types in the system.
INFO: 2022-Apr-22 15:07:21: Periodic flag for the system is set to true.
INFO: 2022-Apr-22 15:07:21: Finished reading system coordinates from plane.dat.
INFO: 2022-Apr-22 15:07:21: Created cell list with 3267 cells.
INFO: 2022-Apr-22 15:07:21: Each cell has dimensions (3.0303030303030303,3.0303030303030303,3.3333333333333335).
INFO: 2022-Apr-22 15:07:21: Using cell lists for neighbour list builds.
WARNING: 2022-Apr-22 15:07:21: Neighbour list. No maximum face perimeter set. Assuming default value of 20.
INFO: 2022-Apr-22 15:07:21: Neighbour list. Using geometric centers for mesh dual.
INFO: 2022-Apr-22 15:07:21: Created neighbour list with cutoff 2.5 and padding distance 0.5.
INFO: 2022-Apr-22 15:07:21: Dump type set to full
WARNING: 2022-Apr-22 15:07:21: No dump directory specified. Using current directory.
INFO: 2022-Apr-22 15:07:21: Dump will be sent to the file with base name plane_test with extension dat.
INFO: 2022-Apr-22 15:07:21: Dumping will start after 0 time steps.
INFO: 2022-Apr-22 15:07:21: Dump will be produced every 10000 time steps.
INFO: 2022-Apr-22 15:07:21: Each dumped time step will be stored in a separate file labelled by the time step.
INFO: 2022-Apr-22 15:07:21: Include info header into the dump file.
INFO: 2022-Apr-22 15:07:21: Adding dump to file plane_test.
INFO: 2022-Apr-22 15:07:21: Setting flag coordinate for dump plane_test.
INFO: 2022-Apr-22 15:07:21: Setting flag director for dump plane_test.
INFO: 2022-Apr-22 15:07:21: Setting flag flag for dump plane_test.
INFO: 2022-Apr-22 15:07:21: Parameter freq for dump plane_test is set to 10000.
INFO: 2022-Apr-22 15:07:21: Setting flag header for dump plane_test.
INFO: 2022-Apr-22 15:07:21: Setting flag id for dump plane_test.
INFO: 2022-Apr-22 15:07:21: Setting flag multi for dump plane_test.
INFO: 2022-Apr-22 15:07:21: Setting flag radius for dump plane_test.
INFO: 2022-Apr-22 15:07:21: Parameter start for dump plane_test is set to 0.
INFO: 2022-Apr-22 15:07:21: Setting flag tp for dump plane_test.
INFO: 2022-Apr-22 15:07:21: Parameter type for dump plane_test is set to full.
INFO: 2022-Apr-22 15:07:21: Setting flag velocity for dump plane_test.
INFO: 2022-Apr-22 15:07:21: Dump type set to vtp
WARNING: 2022-Apr-22 15:07:21: No dump directory specified. Using current directory.
INFO: 2022-Apr-22 15:07:21: Dump will be sent to the file with base name plane_test with extension vtp.
INFO: 2022-Apr-22 15:07:21: Dumping will start after 0 time steps.
INFO: 2022-Apr-22 15:07:21: Dump will be produced every 1000 time steps.
WARNING: 2022-Apr-22 15:07:21: All time steps will be concatenated to a single file.
INFO: 2022-Apr-22 15:07:21: Adding dump to file plane_test.
INFO: 2022-Apr-22 15:07:21: Parameter freq for dump plane_test is set to 1000.
INFO: 2022-Apr-22 15:07:21: Parameter start for dump plane_test is set to 0.
INFO: 2022-Apr-22 15:07:21: Parameter type for dump plane_test is set to vtp.
WARNING: 2022-Apr-22 15:07:21: Constraint. Maximum number of iterations has not been set. Assuming 100
WARNING: 2022-Apr-22 15:07:21: Constraint. Tolerance has not been set. Assuming 1e-6.
WARNING: 2022-Apr-22 15:07:21: Constraint. No particle groups set. Assuming "all".
INFO: 2022-Apr-22 15:07:21: Planar constraint. Setting plane dimensions to lx = 100 and ly = 100.
WARNING: 2022-Apr-22 15:07:21: Plane constraint. For non-periodic systems particle motion will be confined by the box size.
WARNING: 2022-Apr-22 15:07:21: Plane constraint. No zpos specified. Assuming that the constraint plane is at z = 0.
INFO: 2022-Apr-22 15:07:21: Added  : plane to the list of constraints.
INFO: 2022-Apr-22 15:07:21: Adding constraint of type plane.
WARNING: 2022-Apr-22 15:07:21: Value object. No minimum value set. Assuming 0.
WARNING: 2022-Apr-22 15:07:21: Value object. No maximum value set. Assuming 1.0.
WARNING: 2022-Apr-22 15:07:21: Value object. No number of steps set. Assuming 1000.
INFO: 2022-Apr-22 15:07:21: Using constant value object.
WARNING: 2022-Apr-22 15:07:21: Number of particle types has to be equal or greater than the number of types defined in the intial configuation. Using value read from the intial configuration.
INFO: 2022-Apr-22 15:07:21: Global potential strength (k) for soft pair potential is set to 1.0.
WARNING: 2022-Apr-22 15:07:21: No potential range (a) specified for soft pair potential. Setting it to 2.
INFO: 2022-Apr-22 15:07:21: Added pair potential : soft to the list of pair interactions.
INFO: 2022-Apr-22 15:07:21: Pair potential soft has neighbour list. Neighbour list updates will be performed during the simulation.
INFO: 2022-Apr-22 15:07:21: Added soft to the list of pair potentials.
INFO: 2022-Apr-22 15:07:21: Added logger. Logged quantities will be sent to plane_test.log.
INFO: 2022-Apr-22 15:07:21: Logs will be produced every 1000 time steps.
INFO: 2022-Apr-22 15:07:21: Adding log quantity : soft_energy.
INFO: 2022-Apr-22 15:07:21: Adding log quantity : velocity.
INFO: 2022-Apr-22 15:07:21: Adding logger to file plane_test.log.
WARNING: 2022-Apr-22 15:07:21: Value object. No minimum value set. Assuming 0.
WARNING: 2022-Apr-22 15:07:21: Value object. No maximum value set. Assuming 1.0.
WARNING: 2022-Apr-22 15:07:21: Value object. No number of steps set. Assuming 1000.
INFO: 2022-Apr-22 15:07:21: Using constant value object.
WARNING: 2022-Apr-22 15:07:21: Integrator is setting its own time step size. While this is allowed, it may cause odd behaviour in case different integrators set different internal step size.
INFO: 2022-Apr-22 15:07:21: Internal integrator time step set to 0.001.
WARNING: 2022-Apr-22 15:07:21: No group has been set. Assuming group 'all'.
WARNING: 2022-Apr-22 15:07:21: NVE integrator has limit on the maximum particle displacement. It is set to 0.0001.
INFO: 2022-Apr-22 15:07:21: Adding integrator of type nve (for group all).
INFO: 2022-Apr-22 15:07:21: Starting simulation run for 10000 steps.
INFO: 2022-Apr-22 15:07:33: Built neighbour list 4 time. Average number of steps between two builds : 2500.
INFO: 2022-Apr-22 15:07:33: Disabling integrator nve_all.
INFO: 2022-Apr-22 15:07:33: Adding particle to group g.
INFO: 2022-Apr-22 15:07:33: Added 272 particles to group g.
INFO: 2022-Apr-22 15:07:33: Adding group g.
INFO: 2022-Apr-22 15:07:33: Adding particle to group p.
INFO: 2022-Apr-22 15:07:33: Added 2911 particles to group p.
INFO: 2022-Apr-22 15:07:33: Adding group p.
WARNING: 2022-Apr-22 15:07:33: Value object. No minimum value set. Assuming 0.
WARNING: 2022-Apr-22 15:07:33: Value object. No maximum value set. Assuming 1.0.
WARNING: 2022-Apr-22 15:07:33: Value object. No number of steps set. Assuming 1000.
INFO: 2022-Apr-22 15:07:33: Using constant value object.
WARNING: 2022-Apr-22 15:07:33: Integrator is setting its own time step size. While this is allowed, it may cause odd behaviour in case different integrators set different internal step size.
INFO: 2022-Apr-22 15:07:33: Internal integrator time step set to 0.001.
WARNING: 2022-Apr-22 15:07:33: No group has been set. Assuming group 'all'.
WARNING: 2022-Apr-22 15:07:33: Brownian dynamics is a legacy integrator keep for backwards compatibility. It will be removed in a later release. Please consider using brawnian_pos and brownian_align instead.
INFO: 2022-Apr-22 15:07:33: Brownian dynamics integrator. Setting magnitude of active velocity to 0.5.
INFO: 2022-Apr-22 15:07:33: Brownian dynamics integrator. Setting rotational diffusion rate to 0.8.
INFO: 2022-Apr-22 15:07:33: Brownian dynamics integrator. Setting mobility to 1.0.
WARNING: 2022-Apr-22 15:07:33: Brownian dynamics integrator. Rotational mobility not set. Using default value 1.
INFO: 2022-Apr-22 15:07:33: Brownian dynamics integrator. Setting random number generator seed to 1.
WARNING: 2022-Apr-22 15:07:33: Brownian dynamics integrator. Assuming polar order parameter.
INFO: 2022-Apr-22 15:07:33: Adding integrator of type brownian (for group all).
INFO: 2022-Apr-22 15:07:33: Population. Applying population to group g.
INFO: 2022-Apr-22 15:07:33: Population. Population control frequency set to 100.
WARNING: 2022-Apr-22 15:07:33: Density population control. No random number generator seed specified. Using default 0.
INFO: 2022-Apr-22 15:07:33: Density population control. Setting division rate 0.1.
INFO: 2022-Apr-22 15:07:33: Density population control. Setting death rate 0.0.
INFO: 2022-Apr-22 15:07:33: Density population control. Setting particle type change probability for first child to 0.0.
INFO: 2022-Apr-22 15:07:33: Density population control. Setting particle type change probability for second child to 1.0.
INFO: 2022-Apr-22 15:07:33: Density population control. Type of new particle type set to 1.
WARNING: 2022-Apr-22 15:07:33: Density population control. No new particle radius set. Using default 0 (i.e. inherit from mother).
WARNING: 2022-Apr-22 15:07:33: Density population control. No polydispersity set. Using default 0.
INFO: 2022-Apr-22 15:07:33: Density population control. Old group set to g.
INFO: 2022-Apr-22 15:07:33: Density population control. New group set to p.
INFO: 2022-Apr-22 15:07:33: Density population control. Split distance set to 2.0.
WARNING: 2022-Apr-22 15:07:33: Density population control. No maximum density set. Using default 8.
WARNING: 2022-Apr-22 15:07:33: Density population control. No split of the offspring separation set. Assuming 0.5.
INFO: 2022-Apr-22 15:07:33: Adding population of type density (for group g).
INFO: 2022-Apr-22 15:07:33: Population. Applying population to group p.
INFO: 2022-Apr-22 15:07:33: Population. Population control frequency set to 100.
WARNING: 2022-Apr-22 15:07:33: Density population control. No random number generator seed specified. Using default 0.
INFO: 2022-Apr-22 15:07:33: Density population control. Setting division rate 0.0.
INFO: 2022-Apr-22 15:07:33: Density population control. Setting death rate 1e-4.
INFO: 2022-Apr-22 15:07:33: Density population control. Setting particle type change probability for first child to 0.0.
INFO: 2022-Apr-22 15:07:33: Density population control. Setting particle type change probability for second child to 0.0.
WARNING: 2022-Apr-22 15:07:33: Density population control. No new particle type set. Using default 0.
WARNING: 2022-Apr-22 15:07:33: Density population control. No new particle radius set. Using default 0 (i.e. inherit from mother).
WARNING: 2022-Apr-22 15:07:33: Density population control. No polydispersity set. Using default 0.
WARNING: 2022-Apr-22 15:07:33: Density population control. No old group set. Using default "all".
WARNING: 2022-Apr-22 15:07:33: Density population control. No new group set. Using default "all".
WARNING: 2022-Apr-22 15:07:33: Density population control. No split distance set. Using default 0.5.
WARNING: 2022-Apr-22 15:07:33: Density population control. No maximum density set. Using default 8.
WARNING: 2022-Apr-22 15:07:33: Density population control. No split of the offspring separation set. Assuming 0.5.
INFO: 2022-Apr-22 15:07:33: Adding population of type density (for group p).
INFO: 2022-Apr-22 15:07:33: Reading dummy keyword ntypes.
INFO: 2022-Apr-22 15:07:33: Starting simulation run for 1000000 steps.
INFO: 2022-Apr-22 15:28:17: Built neighbour list 20000 time. Average number of steps between two builds : 50.
INFO: 2022-Apr-22 15:28:17: Simulation took 0 hours, 20 minutes and 56 seconds (1256 seconds).
INFO: 2022-Apr-22 15:28:17: Average 804.14171974522299 time steps per second.
