INFO: 2022-Apr-22 16:07:26: Messages will be sent to messages.msg.
INFO: 2022-Apr-22 16:07:26: Simulation box is periodic with size (lx,ly,lz) = (100,100,10).
INFO: 2022-Apr-22 16:07:26: Generated group 'all' containing all particles.
INFO: 2022-Apr-22 16:07:26: Reading particle coordinates from file: plane.dat
WARNING: 2022-Apr-22 16:07:26: Input format style '# id type radius' is deprecated and will be removed in a future version.
INFO: 2022-Apr-22 16:07:26: Column 1 of input file is : id.
INFO: 2022-Apr-22 16:07:26: Column 2 of input file is : type.
INFO: 2022-Apr-22 16:07:26: Column 3 of input file is : radius.
INFO: 2022-Apr-22 16:07:26: Column 4 of input file is : x.
INFO: 2022-Apr-22 16:07:26: Column 5 of input file is : y.
INFO: 2022-Apr-22 16:07:26: Column 6 of input file is : z.
INFO: 2022-Apr-22 16:07:26: Column 7 of input file is : vx.
INFO: 2022-Apr-22 16:07:26: Column 8 of input file is : vy.
INFO: 2022-Apr-22 16:07:26: Column 9 of input file is : vz.
INFO: 2022-Apr-22 16:07:26: Column 10 of input file is : nx.
INFO: 2022-Apr-22 16:07:26: Column 11 of input file is : ny.
INFO: 2022-Apr-22 16:07:26: Column 12 of input file is : nz.
INFO: 2022-Apr-22 16:07:26: Column 13 of input file is : omega.
INFO: 2022-Apr-22 16:07:26: Read data for 3183 particles.
INFO: 2022-Apr-22 16:07:26: There are 2 distinct particle types in the system.
INFO: 2022-Apr-22 16:07:26: Periodic flag for the system is set to true.
INFO: 2022-Apr-22 16:07:26: Finished reading system coordinates from plane.dat.
INFO: 2022-Apr-22 16:07:26: Created cell list with 3267 cells.
INFO: 2022-Apr-22 16:07:26: Each cell has dimensions (3.0303030303030303,3.0303030303030303,3.3333333333333335).
INFO: 2022-Apr-22 16:07:26: Using cell lists for neighbour list builds.
WARNING: 2022-Apr-22 16:07:26: Neighbour list. No maximum face perimeter set. Assuming default value of 20.
INFO: 2022-Apr-22 16:07:26: Neighbour list. Using geometric centers for mesh dual.
INFO: 2022-Apr-22 16:07:26: Created neighbour list with cutoff 2.5 and padding distance 0.5.
INFO: 2022-Apr-22 16:07:26: Dump type set to velocity
WARNING: 2022-Apr-22 16:07:26: No dump directory specified. Using current directory.
INFO: 2022-Apr-22 16:07:26: Dump will be sent to the file with base name plane_test with extension vel.
INFO: 2022-Apr-22 16:07:26: Dumping will start after 0 time steps.
INFO: 2022-Apr-22 16:07:26: Dump will be produced every 10000 time steps.
INFO: 2022-Apr-22 16:07:26: Each dumped time step will be stored in a separate file labelled by the time step.
INFO: 2022-Apr-22 16:07:26: Include info header into the dump file.
INFO: 2022-Apr-22 16:07:26: Adding dump to file plane_test.
INFO: 2022-Apr-22 16:07:26: Parameter freq for dump plane_test is set to 10000.
INFO: 2022-Apr-22 16:07:26: Setting flag header for dump plane_test.
INFO: 2022-Apr-22 16:07:26: Setting flag multi for dump plane_test.
INFO: 2022-Apr-22 16:07:26: Parameter start for dump plane_test is set to 0.
INFO: 2022-Apr-22 16:07:26: Parameter type for dump plane_test is set to velocity.
INFO: 2022-Apr-22 16:07:26: Dump type set to xyz
WARNING: 2022-Apr-22 16:07:26: No dump directory specified. Using current directory.
INFO: 2022-Apr-22 16:07:26: Dump will be sent to the file with base name plane_test with extension xyz.
INFO: 2022-Apr-22 16:07:26: Dumping will start after 0 time steps.
INFO: 2022-Apr-22 16:07:26: Dump will be produced every 10000 time steps.
INFO: 2022-Apr-22 16:07:26: Each dumped time step will be stored in a separate file labelled by the time step.
INFO: 2022-Apr-22 16:07:26: Include info header into the dump file.
INFO: 2022-Apr-22 16:07:26: Adding dump to file plane_test.
INFO: 2022-Apr-22 16:07:26: Parameter freq for dump plane_test is set to 10000.
INFO: 2022-Apr-22 16:07:26: Setting flag header for dump plane_test.
INFO: 2022-Apr-22 16:07:26: Setting flag multi for dump plane_test.
INFO: 2022-Apr-22 16:07:26: Parameter start for dump plane_test is set to 0.
INFO: 2022-Apr-22 16:07:26: Parameter type for dump plane_test is set to xyz.
INFO: 2022-Apr-22 16:07:26: Dump type set to dcd
WARNING: 2022-Apr-22 16:07:26: No dump directory specified. Using current directory.
INFO: 2022-Apr-22 16:07:26: Dump will be sent to the file with base name plane_test with extension dcd.
INFO: 2022-Apr-22 16:07:26: Dumping will start after 0 time steps.
INFO: 2022-Apr-22 16:07:26: Dump will be produced every 1000 time steps.
WARNING: 2022-Apr-22 16:07:26: All time steps will be concatenated to a single file.
INFO: 2022-Apr-22 16:07:26: Adding dump to file plane_test.
INFO: 2022-Apr-22 16:07:26: Parameter freq for dump plane_test is set to 1000.
INFO: 2022-Apr-22 16:07:26: Parameter start for dump plane_test is set to 0.
INFO: 2022-Apr-22 16:07:26: Parameter type for dump plane_test is set to dcd.
INFO: 2022-Apr-22 16:07:27: Dump type set to xyzv
WARNING: 2022-Apr-22 16:07:27: No dump directory specified. Using current directory.
INFO: 2022-Apr-22 16:07:27: Dump will be sent to the file with base name plane_test_dir with extension xyzv.
INFO: 2022-Apr-22 16:07:27: Dumping will start after 0 time steps.
INFO: 2022-Apr-22 16:07:27: Dump will be produced every 1000 time steps.
WARNING: 2022-Apr-22 16:07:27: All time steps will be concatenated to a single file.
INFO: 2022-Apr-22 16:07:27: Include info header into the dump file.
INFO: 2022-Apr-22 16:07:27: Adding dump to file plane_test_dir.
INFO: 2022-Apr-22 16:07:27: Parameter freq for dump plane_test_dir is set to 1000.
INFO: 2022-Apr-22 16:07:27: Setting flag header for dump plane_test_dir.
INFO: 2022-Apr-22 16:07:27: Parameter scale for dump plane_test_dir is set to 0.25.
INFO: 2022-Apr-22 16:07:27: Parameter start for dump plane_test_dir is set to 0.
INFO: 2022-Apr-22 16:07:27: Parameter type for dump plane_test_dir is set to xyzv.
INFO: 2022-Apr-22 16:07:27: Dump type set to xyzv
WARNING: 2022-Apr-22 16:07:27: No dump directory specified. Using current directory.
INFO: 2022-Apr-22 16:07:27: Dump will be sent to the file with base name plane_test_vel with extension xyzv.
INFO: 2022-Apr-22 16:07:27: Dumping will start after 0 time steps.
INFO: 2022-Apr-22 16:07:27: Dump will be produced every 1000 time steps.
WARNING: 2022-Apr-22 16:07:27: All time steps will be concatenated to a single file.
INFO: 2022-Apr-22 16:07:27: Include info header into the dump file.
INFO: 2022-Apr-22 16:07:27: Adding dump to file plane_test_vel.
INFO: 2022-Apr-22 16:07:27: Parameter freq for dump plane_test_vel is set to 1000.
INFO: 2022-Apr-22 16:07:27: Setting flag header for dump plane_test_vel.
INFO: 2022-Apr-22 16:07:27: Parameter scale for dump plane_test_vel is set to 0.1.
INFO: 2022-Apr-22 16:07:27: Parameter start for dump plane_test_vel is set to 0.
INFO: 2022-Apr-22 16:07:27: Parameter type for dump plane_test_vel is set to xyzv.
INFO: 2022-Apr-22 16:07:27: Setting flag velocity for dump plane_test_vel.
INFO: 2022-Apr-22 16:07:27: Dump type set to full
WARNING: 2022-Apr-22 16:07:27: No dump directory specified. Using current directory.
INFO: 2022-Apr-22 16:07:27: Dump will be sent to the file with base name plane_test with extension dat.
INFO: 2022-Apr-22 16:07:27: Dumping will start after 0 time steps.
INFO: 2022-Apr-22 16:07:27: Dump will be produced every 1000 time steps.
INFO: 2022-Apr-22 16:07:27: Each dumped time step will be stored in a separate file labelled by the time step.
INFO: 2022-Apr-22 16:07:27: Include info header into the dump file.
INFO: 2022-Apr-22 16:07:27: Adding dump to file plane_test.
INFO: 2022-Apr-22 16:07:27: Setting flag coordinate for dump plane_test.
INFO: 2022-Apr-22 16:07:27: Setting flag director for dump plane_test.
INFO: 2022-Apr-22 16:07:27: Parameter freq for dump plane_test is set to 1000.
INFO: 2022-Apr-22 16:07:27: Setting flag header for dump plane_test.
INFO: 2022-Apr-22 16:07:27: Setting flag multi for dump plane_test.
INFO: 2022-Apr-22 16:07:27: Parameter start for dump plane_test is set to 0.
INFO: 2022-Apr-22 16:07:27: Parameter type for dump plane_test is set to full.
INFO: 2022-Apr-22 16:07:27: Setting flag velocity for dump plane_test.
INFO: 2022-Apr-22 16:07:27: Dump type set to vtp
WARNING: 2022-Apr-22 16:07:27: No dump directory specified. Using current directory.
INFO: 2022-Apr-22 16:07:27: Dump will be sent to the file with base name plane_test with extension vtp.
INFO: 2022-Apr-22 16:07:27: Dumping will start after 0 time steps.
INFO: 2022-Apr-22 16:07:27: Dump will be produced every 1000 time steps.
WARNING: 2022-Apr-22 16:07:27: All time steps will be concatenated to a single file.
INFO: 2022-Apr-22 16:07:27: Adding dump to file plane_test.
INFO: 2022-Apr-22 16:07:27: Parameter freq for dump plane_test is set to 1000.
INFO: 2022-Apr-22 16:07:27: Parameter start for dump plane_test is set to 0.
INFO: 2022-Apr-22 16:07:27: Parameter type for dump plane_test is set to vtp.
WARNING: 2022-Apr-22 16:07:27: Constraint. Maximum number of iterations has not been set. Assuming 100
WARNING: 2022-Apr-22 16:07:27: Constraint. Tolerance has not been set. Assuming 1e-6.
WARNING: 2022-Apr-22 16:07:27: Constraint. No particle groups set. Assuming "all".
INFO: 2022-Apr-22 16:07:27: Planar constraint. Setting plane dimensions to lx = 100 and ly = 100.
WARNING: 2022-Apr-22 16:07:27: Plane constraint. For non-periodic systems particle motion will be confined by the box size.
WARNING: 2022-Apr-22 16:07:27: Plane constraint. No zpos specified. Assuming that the constraint plane is at z = 0.
INFO: 2022-Apr-22 16:07:27: Added  : plane to the list of constraints.
INFO: 2022-Apr-22 16:07:27: Adding constraint of type plane.
WARNING: 2022-Apr-22 16:07:27: Value object. No minimum value set. Assuming 0.
WARNING: 2022-Apr-22 16:07:27: Value object. No maximum value set. Assuming 1.0.
WARNING: 2022-Apr-22 16:07:27: Value object. No number of steps set. Assuming 1000.
INFO: 2022-Apr-22 16:07:27: Using constant value object.
WARNING: 2022-Apr-22 16:07:27: Number of particle types will be read from the intitial configuration.
INFO: 2022-Apr-22 16:07:27: Global potential strength (k) for soft pair potential is set to 1.0.
WARNING: 2022-Apr-22 16:07:27: No potential range (a) specified for soft pair potential. Setting it to 2.
INFO: 2022-Apr-22 16:07:27: Added pair potential : soft to the list of pair interactions.
INFO: 2022-Apr-22 16:07:27: Pair potential soft has neighbour list. Neighbour list updates will be performed during the simulation.
INFO: 2022-Apr-22 16:07:27: Added soft to the list of pair potentials.
INFO: 2022-Apr-22 16:07:27: Global coupling constant (J) for polar alignment is set to 1.0.
WARNING: 2022-Apr-22 16:07:27: No cutoff distance (rcut) specified for polar alignment. Setting it to the global neighbour list cutoff.
INFO: 2022-Apr-22 16:07:27: Added pairwise alignment : polar to the list of pair alignments.
INFO: 2022-Apr-22 16:07:27: Pairwise alignment polar has neighbour list. Neighbour list updates will be performed during the simulation.
INFO: 2022-Apr-22 16:07:27: Added polar to the list of pairwise aligners.
INFO: 2022-Apr-22 16:07:27: Setting global integrator timestep to 0.001.
WARNING: 2022-Apr-22 16:07:27: Value object. No minimum value set. Assuming 0.
WARNING: 2022-Apr-22 16:07:27: Value object. No maximum value set. Assuming 1.0.
WARNING: 2022-Apr-22 16:07:27: Value object. No number of steps set. Assuming 1000.
INFO: 2022-Apr-22 16:07:27: Using constant value object.
INFO: 2022-Apr-22 16:07:27: Using global (system-wide) integrator step size set to 0.001.
WARNING: 2022-Apr-22 16:07:27: No group has been set. Assuming group 'all'.
WARNING: 2022-Apr-22 16:07:27: NVE integrator has limit on the maximum particle displacement. It is set to 0.0001.
INFO: 2022-Apr-22 16:07:27: Adding integrator of type nve (for group all).
INFO: 2022-Apr-22 16:07:27: Starting simulation run for 10000 steps.
INFO: 2022-Apr-22 16:07:43: Built neighbour list 4 time. Average number of steps between two builds : 2500.
INFO: 2022-Apr-22 16:07:43: Disabling integrator nve_all.
INFO: 2022-Apr-22 16:07:43: Activity in self propulsion set to 1.0.
INFO: 2022-Apr-22 16:07:43: Added external potential : self_propulsion to the list of external forces.
INFO: 2022-Apr-22 16:07:43: Added self_propulsion to the list of external potentials.
INFO: 2022-Apr-22 16:07:43: Setting global integrator timestep to 0.01.
WARNING: 2022-Apr-22 16:07:43: Value object. No minimum value set. Assuming 0.
WARNING: 2022-Apr-22 16:07:43: Value object. No maximum value set. Assuming 1.0.
WARNING: 2022-Apr-22 16:07:43: Value object. No number of steps set. Assuming 1000.
INFO: 2022-Apr-22 16:07:43: Using constant value object.
INFO: 2022-Apr-22 16:07:43: Using global (system-wide) integrator step size set to 0.01.
INFO: 2022-Apr-22 16:07:43: Applying integrator to group all.
INFO: 2022-Apr-22 16:07:43: Brownian dynamics integrator for particle position. Setting mobility to 1.0.
INFO: 2022-Apr-22 16:07:43: Brownian dynamics integrator for particle position. Setting random number generator seed to 1.
INFO: 2022-Apr-22 16:07:43: Adding integrator of type brownian_pos (for group all).
WARNING: 2022-Apr-22 16:07:43: Value object. No minimum value set. Assuming 0.
WARNING: 2022-Apr-22 16:07:43: Value object. No maximum value set. Assuming 1.0.
WARNING: 2022-Apr-22 16:07:43: Value object. No number of steps set. Assuming 1000.
INFO: 2022-Apr-22 16:07:43: Using constant value object.
INFO: 2022-Apr-22 16:07:43: Using global (system-wide) integrator step size set to 0.01.
INFO: 2022-Apr-22 16:07:43: Applying integrator to group all.
INFO: 2022-Apr-22 16:07:43: Brownian dynamics integrator for alignment. Setting rotational diffusion rate to 0.1.
INFO: 2022-Apr-22 16:07:43: Brownian dynamics integrator for alignment. Setting rotational mobility to 1.0.
INFO: 2022-Apr-22 16:07:43: Brownian dynamics integrator for alignment. Setting random number generator seed to 1.
WARNING: 2022-Apr-22 16:07:43: Brownian dynamics integrator for alignment. Assuming polar order parameter.
INFO: 2022-Apr-22 16:07:43: Adding integrator of type brownian_align (for group all).
INFO: 2022-Apr-22 16:07:43: Starting simulation run for 50000 steps.
INFO: 2022-Apr-22 16:09:21: Built neighbour list 2270 time. Average number of steps between two builds : 22.026431718061673.
INFO: 2022-Apr-22 16:09:21: Simulation took 0 hours, 1 minutes and 55 seconds (115 seconds).
INFO: 2022-Apr-22 16:09:21: Average 521.75652173913045 time steps per second.
