INFO: 2022-Apr-22 14:23:49: Messages will be sent to messages.msg.
INFO: 2022-Apr-22 14:23:49: Adding config file sphere of type json.
INFO: 2022-Apr-22 14:23:49: Simulation box is fixed with size (lx,ly,lz) = (30,30,30).
INFO: 2022-Apr-22 14:23:49: Generated group 'all' containing all particles.
INFO: 2022-Apr-22 14:23:49: Reading particle coordinates from file: sphere.dat
INFO: 2022-Apr-22 14:23:49: Column 1 of input file is : id.
INFO: 2022-Apr-22 14:23:49: Column 2 of input file is : type.
INFO: 2022-Apr-22 14:23:49: Column 3 of input file is : radius.
INFO: 2022-Apr-22 14:23:49: Column 4 of input file is : x.
INFO: 2022-Apr-22 14:23:49: Column 5 of input file is : y.
INFO: 2022-Apr-22 14:23:49: Column 6 of input file is : z.
INFO: 2022-Apr-22 14:23:49: Column 7 of input file is : vx.
INFO: 2022-Apr-22 14:23:49: Column 8 of input file is : vy.
INFO: 2022-Apr-22 14:23:49: Column 9 of input file is : vz.
INFO: 2022-Apr-22 14:23:49: Column 10 of input file is : nx.
INFO: 2022-Apr-22 14:23:49: Column 11 of input file is : ny.
INFO: 2022-Apr-22 14:23:49: Column 12 of input file is : nz.
INFO: 2022-Apr-22 14:23:50: Read data for 800 particles.
INFO: 2022-Apr-22 14:23:50: There are 1 distinct particle types in the system.
INFO: 2022-Apr-22 14:23:50: Periodic flag for the system is set to false.
INFO: 2022-Apr-22 14:23:50: Finished reading system coordinates from sphere.dat.
INFO: 2022-Apr-22 14:23:50: Created cell list with 1000 cells.
INFO: 2022-Apr-22 14:23:50: Each cell has dimensions (3,3,3).
INFO: 2022-Apr-22 14:23:50: Using cell lists for neighbour list builds.
WARNING: 2022-Apr-22 14:23:50: Neighbour list. No maximum face perimeter set. Assuming default value of 20.
INFO: 2022-Apr-22 14:23:50: Neighbour list. Using geometric centers for mesh dual.
INFO: 2022-Apr-22 14:23:50: Created neighbour list with cutoff 2.3999999999999999 and padding distance 0.5.
INFO: 2022-Apr-22 14:23:50: Dump type set to vtp
WARNING: 2022-Apr-22 14:23:50: No dump directory specified. Using current directory.
INFO: 2022-Apr-22 14:23:50: Dump will be sent to the file with base name sphere with extension vtp.
INFO: 2022-Apr-22 14:23:50: Dumping will start after 0 time steps.
INFO: 2022-Apr-22 14:23:50: Dump will be produced every 1000 time steps.
INFO: 2022-Apr-22 14:23:50: Each dumped time step will be stored in a separate file labelled by the time step.
INFO: 2022-Apr-22 14:23:50: Adding dump to file sphere.
INFO: 2022-Apr-22 14:23:50: Parameter freq for dump sphere is set to 1000.
INFO: 2022-Apr-22 14:23:50: Setting flag multi for dump sphere.
INFO: 2022-Apr-22 14:23:50: Parameter start for dump sphere is set to 0.
INFO: 2022-Apr-22 14:23:50: Parameter type for dump sphere is set to vtp.
INFO: 2022-Apr-22 14:23:50: Dump type set to full
WARNING: 2022-Apr-22 14:23:50: No dump directory specified. Using current directory.
INFO: 2022-Apr-22 14:23:50: Dump will be sent to the file with base name sphere with extension dat.
INFO: 2022-Apr-22 14:23:50: Dumping will start after 0 time steps.
INFO: 2022-Apr-22 14:23:50: Dump will be produced every 1000 time steps.
INFO: 2022-Apr-22 14:23:50: Each dumped time step will be stored in a separate file labelled by the time step.
INFO: 2022-Apr-22 14:23:50: Include keys line into the dump file.
INFO: 2022-Apr-22 14:23:50: Adding dump to file sphere.
INFO: 2022-Apr-22 14:23:50: Setting flag coordinate for dump sphere.
INFO: 2022-Apr-22 14:23:50: Setting flag director for dump sphere.
INFO: 2022-Apr-22 14:23:50: Parameter freq for dump sphere is set to 1000.
INFO: 2022-Apr-22 14:23:50: Setting flag id for dump sphere.
INFO: 2022-Apr-22 14:23:50: Setting flag keys for dump sphere.
INFO: 2022-Apr-22 14:23:50: Setting flag multi for dump sphere.
INFO: 2022-Apr-22 14:23:50: Setting flag radius for dump sphere.
INFO: 2022-Apr-22 14:23:50: Parameter start for dump sphere is set to 0.
INFO: 2022-Apr-22 14:23:50: Parameter type for dump sphere is set to full.
INFO: 2022-Apr-22 14:23:50: Setting flag velocity for dump sphere.
WARNING: 2022-Apr-22 14:23:50: Constraint. Maximum number of iterations has not been set. Assuming 100
WARNING: 2022-Apr-22 14:23:50: Constraint. Tolerance has not been set. Assuming 1e-6.
WARNING: 2022-Apr-22 14:23:50: Constraint. No particle groups set. Assuming "all".
INFO: 2022-Apr-22 14:23:50: Spherical constraint. Radius set to 10.
INFO: 2022-Apr-22 14:23:50: Added  : sphere to the list of constraints.
INFO: 2022-Apr-22 14:23:50: Adding constraint of type sphere.
WARNING: 2022-Apr-22 14:23:50: Value object. No minimum value set. Assuming 0.
WARNING: 2022-Apr-22 14:23:50: Value object. No maximum value set. Assuming 1.0.
WARNING: 2022-Apr-22 14:23:50: Value object. No number of steps set. Assuming 1000.
INFO: 2022-Apr-22 14:23:50: Using constant value object.
WARNING: 2022-Apr-22 14:23:50: Number of particle types will be read from the intitial configuration.
INFO: 2022-Apr-22 14:23:50: Global potential strength (k) for soft pair potential is set to 10.0.
INFO: 2022-Apr-22 14:23:50: Global potential range (a) for soft pair potential is set to 1.0.
INFO: 2022-Apr-22 14:23:50: Added pair potential : soft to the list of pair interactions.
INFO: 2022-Apr-22 14:23:50: Pair potential soft has neighbour list. Neighbour list updates will be performed during the simulation.
INFO: 2022-Apr-22 14:23:50: Added soft to the list of pair potentials.
INFO: 2022-Apr-22 14:23:50: Global coupling constant (J) for polar alignment is set to 1.0.
WARNING: 2022-Apr-22 14:23:50: No cutoff distance (rcut) specified for polar alignment. Setting it to the global neighbour list cutoff.
INFO: 2022-Apr-22 14:23:50: Added pairwise alignment : polar to the list of pair alignments.
INFO: 2022-Apr-22 14:23:50: Pairwise alignment polar has neighbour list. Neighbour list updates will be performed during the simulation.
INFO: 2022-Apr-22 14:23:50: Added polar to the list of pairwise aligners.
INFO: 2022-Apr-22 14:23:50: Added logger. Logged quantities will be sent to sphere.log.
INFO: 2022-Apr-22 14:23:50: Logs will be produced every 100 time steps.
INFO: 2022-Apr-22 14:23:50: Adding log quantity : polar_align.
INFO: 2022-Apr-22 14:23:50: Adding log quantity : soft_energy.
INFO: 2022-Apr-22 14:23:50: Adding log quantity : velocity.
INFO: 2022-Apr-22 14:23:50: Adding logger to file sphere.log.
INFO: 2022-Apr-22 14:23:50: Setting global integrator timestep to 0.01.
WARNING: 2022-Apr-22 14:23:50: Value object. No minimum value set. Assuming 0.
WARNING: 2022-Apr-22 14:23:50: Value object. No maximum value set. Assuming 1.0.
WARNING: 2022-Apr-22 14:23:50: Value object. No number of steps set. Assuming 1000.
INFO: 2022-Apr-22 14:23:50: Using constant value object.
INFO: 2022-Apr-22 14:23:50: Using global (system-wide) integrator step size set to 0.01.
WARNING: 2022-Apr-22 14:23:50: No group has been set. Assuming group 'all'.
WARNING: 2022-Apr-22 14:23:50: NVE integrator has limit on the maximum particle displacement. It is set to 0.0001.
INFO: 2022-Apr-22 14:23:50: Adding integrator of type nve (for group all).
INFO: 2022-Apr-22 14:23:50: Starting simulation run for 10000 steps.
INFO: 2022-Apr-22 14:23:54: Built neighbour list 3 time. Average number of steps between two builds : 3333.3333333333335.
INFO: 2022-Apr-22 14:23:54: Disabling integrator nve_all.
INFO: 2022-Apr-22 14:23:54: Activity in self propulsion set to 1.0.
INFO: 2022-Apr-22 14:23:54: Added external potential : self_propulsion to the list of external forces.
INFO: 2022-Apr-22 14:23:54: Added self_propulsion to the list of external potentials.
INFO: 2022-Apr-22 14:23:54: Value object. Minimum value set to 0.1.
WARNING: 2022-Apr-22 14:23:54: Value object. No maximum value set. Assuming 1.0.
WARNING: 2022-Apr-22 14:23:54: Value object. No number of steps set. Assuming 1000.
INFO: 2022-Apr-22 14:23:54: Using constant value object.
INFO: 2022-Apr-22 14:23:54: Using global (system-wide) integrator step size set to 0.01.
WARNING: 2022-Apr-22 14:23:54: No group has been set. Assuming group 'all'.
INFO: 2022-Apr-22 14:23:54: Brownian dynamics integrator for particle position. Setting mobility to 1.0.
INFO: 2022-Apr-22 14:23:54: Brownian dynamics integrator for particle position. Setting random number generator seed to 0.
INFO: 2022-Apr-22 14:23:54: Adding integrator of type brownian_pos (for group all).
WARNING: 2022-Apr-22 14:23:54: Value object. No minimum value set. Assuming 0.
WARNING: 2022-Apr-22 14:23:54: Value object. No maximum value set. Assuming 1.0.
WARNING: 2022-Apr-22 14:23:54: Value object. No number of steps set. Assuming 1000.
INFO: 2022-Apr-22 14:23:54: Using constant value object.
INFO: 2022-Apr-22 14:23:54: Using global (system-wide) integrator step size set to 0.01.
WARNING: 2022-Apr-22 14:23:54: No group has been set. Assuming group 'all'.
INFO: 2022-Apr-22 14:23:54: Brownian dynamics integrator for alignment. Setting rotational diffusion rate to 0.01.
WARNING: 2022-Apr-22 14:23:54: Brownian dynamics integrator for alignment. Rotational mobility not set. Using default value 1.
INFO: 2022-Apr-22 14:23:54: Brownian dynamics integrator for alignment. Setting random number generator seed to 0.
WARNING: 2022-Apr-22 14:23:54: Brownian dynamics integrator for alignment. Assuming polar order parameter.
INFO: 2022-Apr-22 14:23:54: Adding integrator of type brownian_align (for group all).
INFO: 2022-Apr-22 14:23:54: Starting simulation run for 100000 steps.
INFO: 2022-Apr-22 14:25:45: Built neighbour list 37912 time. Average number of steps between two builds : 2.6376872757965817.
INFO: 2022-Apr-22 14:25:45: Simulation took 0 hours, 1 minutes and 56 seconds (116 seconds).
INFO: 2022-Apr-22 14:25:45: Average 948.29310344827582 time steps per second.
